name: TheButtonMCChatPlugin
main: io.github.norbipeti.thebuttonmcchat.PluginMain
version: 4.0
commands:
    u:
        description: Auto-flair system. Accept or ignore flair.
        usage: "&cUsage: /u accept|ignore|opme&r"
    ooc:
        description: Send message in Out-of-Character.
        usage: "&cUsage: /ooc <message>&r"
        alias: nrp
    unlol:
        description: Unlaugh the last laugh.
        alias: unlaugh
    mwiki:
        description: Search the wiki.
        usage: "&cUsage: /mwiki [query]&r"
    dontrunthiscmd:
    tableflip:
        description: Flip a table.
        usage: "&cUsage: /tableflip [message]&r"
    unflip:
        description: Unflip a flip.
        usage: "&cUsage: /unflip [message]&r"
    chatonly:
        description: Enable chat only mode. Useful for chat clients.
        usage: "&cUsage: /chatonly&r"
author: NorbiPeti
depend: [Essentials, Towny, Minigames, Votifier, WorldGuard, WorldEdit, ProtocolLib, FastLogin, Vault, AuthMe]
permissions:
  tbmc.admin:
    description: Gives access to /un- commands and /u admin commands
  tbmc.rainbow:
    description: Gives access to rainbow colors (/u c).
