name: Chroma-Chat
main: buttondevteam.chat.PluginMain
version: '${noprefix.version}'
commands:
  u:
    description: The main command for Chroma-Chat.
  unlol:
    description: Unlaugh the last laugh.
    alias: unlaugh
  mwiki:
    description: Search the wiki.
  tableflip:
    description: Flip a table.
  unflip:
    description: Unflip a flip.
  chatonly:
    description: Enable chat only mode. Useful for chat clients.
  shrug:
    description: Shrug.
  yeehaw:
    description: This command makes you yeehaw.
  waitwhat:
    description: Wait what
    aliases: ww
  lenny:
    description: Lenny face.
  ftop:
    description: Top respect.
  me:
    description: Me command with Chroma support.
author: NorbiPeti
depend:
  - Essentials
- Vault
  - Chroma-Core
soft-depend:
- Dynmap-Towny
- Towny
- dynmap
permissions:
  tbmc.badge.gold:
    description: Gives a patron badge.
    default: false
  tbmc.badge.diamond:
    description: Gives a cool patron badge.
    default: false
api-version: '1.13'
