name: Chroma-Chat
main: buttondevteam.chat.PluginMain
version: '4.0'
commands:
  u:
    description: Auto-flair system. Accept or ignore flair.
  ooc:
    description: Send message Out-of-Character.
    alias: nrp
  unlol:
    description: Unlaugh the last laugh.
    alias: unlaugh
  mwiki:
    description: Search the wiki.
  dontrunthiscmd: null
  tableflip:
    description: Flip a table.
  unflip:
    description: Unflip a flip.
  chatonly:
    description: Enable chat only mode. Useful for chat clients.
  shrug:
    description: Shrug.
  yeehaw:
    description: This command makes you yeehaw.
  waitwhat:
    description: Wait what
    aliases: ww
  lenny:
    description: Lenny face.
  ftop:
    description: Top respect.
author: NorbiPeti
depend:
- Essentials
- Vault
- ChromaCore
soft-depend:
- Minigames
- Dynmap-Towny
- Towny
permissions:
  tbmc.badge.gold:
    description: Gives a patron badge.
    default: false
  tbmc.badge.diamond:
    description: Gives a cool patron badge.
    default: false
api-version: '1.13'
