name: TheButtonMCPlugin
main: tk.sznp.thebuttonautoflair.PluginMain
version: 2.0
commands:
    u:
        description: Auto-flair system. Accept or ignore flair.
        usage: "&cUsage: /u accept|ignore|opme&r"
    rp:
        description: Enable RolePlay mode or say something in RP.
        usage: "&cUsage: /rp [message]&r"
    nrp:
        description: Disable RolePlay mode or say something in non-RP.
        usage: "&cUsage: /nrp [message]&r"
