name: TheButtonMCPlugin
main: tk.sznp.thebuttonautoflair.PluginMain
version: 2.0
commands:
    u:
        description: Auto-flair system. Accept or ignore flair.
        usage: "&cUsage: /u accept|ignore|opme&r"
