name: TheButtonMCPlugin
main: tk.sznp.thebuttonautoflair.PluginMain
version: 3.0
commands:
    u:
        description: Auto-flair system. Accept or ignore flair.
        usage: "&cUsage: /u accept|ignore|opme&r"
    nrp:
        description: Send message in Out-of-Character
        usage: "&cUsage: /nrp <message>&r"
    ooc:
        description: Send message in Out-of-Character
        usage: "&cUsage: /ooc <message>&r"
    unlol:
        description: Unlaugh the last laugh.
    unlaugh:
        description: Unlaugh the last laugh.
author: NorbiPeti
depend: [Essentials, Towny, Minigames]
